network-centric	BEGIN_KP
systems	INSIDE_KP
the	NO_KP
author	NO_KP
describes	NO_KP
a	NO_KP
graduate-level	NO_KP
course	BEGIN_KP
that	NO_KP
addresses	NO_KP
cutting-edge	NO_KP
issues	NO_KP
in	NO_KP
network-centric	BEGIN_KP
systems	INSIDE_KP
while	NO_KP
following	NO_KP
a	NO_KP
more	NO_KP
traditional	NO_KP
graduate	BEGIN_KP
seminar	NO_KP
format	NO_KP
