network	INSIDE_KP
intrusion	INSIDE_KP
and	NO_KP
fault	BEGIN_KP
detection:	NO_KP
a	NO_KP
statistical	BEGIN_KP
anomaly	INSIDE_KP
approach	NO_KP
with	NO_KP
the	NO_KP
advent	NO_KP
and	NO_KP
explosive	NO_KP
growth	NO_KP
of	BEGIN_KP
the	NO_KP
global	NO_KP
internet	BEGIN_KP
and	NO_KP
electronic	BEGIN_KP
commerce	INSIDE_KP
environments,	NO_KP
adaptive/automatic	BEGIN_KP
network/service	INSIDE_KP
intrusion	INSIDE_KP
and	NO_KP
anomaly	BEGIN_KP
detection	INSIDE_KP
in	NO_KP
wide	BEGIN_KP
area	INSIDE_KP
data	INSIDE_KP
networks	INSIDE_KP
and	NO_KP
e-commerce	BEGIN_KP
infrastructures	NO_KP
is	NO_KP
fast	NO_KP
gaining	NO_KP
critical	NO_KP
research	NO_KP
and	NO_KP
practical	NO_KP
importance.	NO_KP
we	NO_KP
present	NO_KP
and	NO_KP
demonstrate	NO_KP
the	NO_KP
use	NO_KP
of	BEGIN_KP
a	NO_KP
general-purpose	NO_KP
hierarchical	BEGIN_KP
multitier	INSIDE_KP
multiwindow	INSIDE_KP
statistical	INSIDE_KP
anomaly	INSIDE_KP
detection	INSIDE_KP
technology	NO_KP
and	NO_KP
system	NO_KP
that	NO_KP
operates	NO_KP
automatically,	NO_KP
adaptively,	NO_KP
and	NO_KP
proactively,	NO_KP
and	NO_KP
can	NO_KP
be	NO_KP
applied	NO_KP
to	NO_KP
various	NO_KP
networking	NO_KP
technologies,	NO_KP
including	NO_KP
both	NO_KP
wired	BEGIN_KP
and	NO_KP
wireless	BEGIN_KP
ad	INSIDE_KP
hoc	INSIDE_KP
networks.	NO_KP
our	NO_KP
method	NO_KP
uses	NO_KP
statistical	BEGIN_KP
models	INSIDE_KP
and	NO_KP
multivariate	BEGIN_KP
classifiers	INSIDE_KP
to	NO_KP
detect	NO_KP
anomalous	NO_KP
network	BEGIN_KP
conditions.	NO_KP
some	NO_KP
numerical	NO_KP
results	NO_KP
are	NO_KP
also	NO_KP
presented	NO_KP
that	NO_KP
demonstrate	NO_KP
that	NO_KP
our	NO_KP
proposed	NO_KP
methodology	NO_KP
can	NO_KP
reliably	NO_KP
detect	NO_KP
attacks	BEGIN_KP
with	NO_KP
traffic	BEGIN_KP
anomaly	INSIDE_KP
intensity	INSIDE_KP
as	NO_KP
low	NO_KP
as	NO_KP
3-5	NO_KP
percent	NO_KP
of	BEGIN_KP
the	NO_KP
typical	NO_KP
background	BEGIN_KP
traffic	INSIDE_KP
intensity,	NO_KP
thus	NO_KP
promising	NO_KP
to	NO_KP
generate	NO_KP
an	NO_KP
effective	NO_KP
early	BEGIN_KP
warning	INSIDE_KP
