holding	NO_KP
on	NO_KP
[workflow	NO_KP
&	NO_KP
content	NO_KP
management]	NO_KP
marc	NO_KP
fresko	NO_KP
of	NO_KP
cornwell	BEGIN_KP
management	INSIDE_KP
consultants	INSIDE_KP
says	NO_KP
'think	NO_KP
ahead'	NO_KP
when	NO_KP
developing	NO_KP
your	NO_KP
electronic	BEGIN_KP
records	INSIDE_KP
management	INSIDE_KP
policy	INSIDE_KP
