the	NO_KP
top	BEGIN_KP
cycle	INSIDE_KP
and	NO_KP
uncovered	BEGIN_KP
solutions	INSIDE_KP
for	NO_KP
weak	BEGIN_KP
tournaments	INSIDE_KP
we	NO_KP
study	NO_KP
axiomatic	BEGIN_KP
properties	NO_KP
of	NO_KP
the	NO_KP
top	BEGIN_KP
cycle	INSIDE_KP
and	NO_KP
uncovered	BEGIN_KP
solutions	INSIDE_KP
for	NO_KP
weak	BEGIN_KP
tournaments.	NO_KP
subsequently,	NO_KP
we	NO_KP
establish	NO_KP
its	NO_KP
connection	NO_KP
with	NO_KP
the	NO_KP
rational	BEGIN_KP
choice	INSIDE_KP
theory	INSIDE_KP
