acts	NO_KP
to	NO_KP
facts	NO_KP
catalogue	BEGIN_KP
the	NO_KP
paper	NO_KP
shows	NO_KP
a	NO_KP
way	NO_KP
to	NO_KP
satisfy	NO_KP
users'	NO_KP
changing	NO_KP
and	NO_KP
specific	NO_KP
information	BEGIN_KP
needs	INSIDE_KP
by	NO_KP
providing	NO_KP
the	NO_KP
modified	NO_KP
format-author-collaborators-title-series-subject	BEGIN_KP
(facts).	NO_KP
catalogue	BEGIN_KP
instead	NO_KP
of	NO_KP
the	NO_KP
traditional	NO_KP
author-collaborator-title-series-subjects	BEGIN_KP
(acts)	NO_KP
catalogue	BEGIN_KP
