name: conversion toolkits test

on: [push]

defaults:
  run:
    shell: bash

jobs:
  unittest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.7']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install OS specific dependencies
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        # TODO https://github.com/apache/incubator-mxnet/issues/18293
        run: sudo apt-get install libopenblas-dev

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Other Dependencies
        run: |
          python -m pip install --user --upgrade pip
          python -m pip install --user setuptools pytest pytest-cov contextvars
          python -m pip install --upgrade cython
          python -m pip install --pre --user "mxnet>=2.0.0b20200802" -f https://dist.mxnet.io/python
          python -m pip install --user -e .[extras]
      - name: Test conversion tools
        run: |
          cd scripts/conversion_toolkits
          bash convert_all.sh
