name: data pipeline end-to-end

on:
  schedule:
    - cron: '0 4 * * *'  # At 04:00, everyday

defaults:
  run:
    shell: bash

jobs:
  unittest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.7' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Test project on AWS Batch
        run: |
          python ./tools/batch/submit-job.py --region us-east-1 \
                                             --job-type c5n.18x \
                                             --source-ref master \
                                             --work-dir . \
                                             --remote https://github.com/dmlc/gluon-nlp \
                                             --command "bash tests/batch_scripts/test_data_pipeline.sh" --wait
