name: continuous build

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  unittest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # TODO Add windows test by using "windows-latest"
        os: [ubuntu-latest, macos-latest]
        python-version: [ '3.6', '3.7', '3.8']
        exclude:
          - os: macos-latest
            python-version: 3.6
          - os: macos-latest
            python-version: 3.8
          - os: ubuntu-latest
            python-version: 3.7
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install OS specific dependencies
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        # TODO https://github.com/apache/incubator-mxnet/issues/18293
        run: sudo apt-get install libopenblas-dev

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Other Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools pytest pytest-cov contextvars
          python -m pip install --upgrade cython
          python -m pip install --pre "mxnet>=2.0.0b20200802" -f https://dist.mxnet.io/python
          python -m pip install -U -e .[extras]
      - name: Run Unittests
        run: |
          python -m pytest --cov=./ --cov-report=xml --device="cpu" --durations=50 tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.10
        with:
          env_vars: OS,PYTHON

      - name: Upload the files generated by the learn + apply subword
        uses: actions/upload-artifact@v2
        with:
          name: learn_apply_subword_ende
          path: tests/process_cli/learn_apply_subword_ende_results/wmt19-test-de-en.*

      - name: Upload the files generated by the learn + apply subword
        uses: actions/upload-artifact@v2
        with:
          name: learn_apply_subword_zh
          path: tests/process_cli/learn_apply_subword_zh_results/wmt19-test-zh-en.*
